// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteControl.Server.Data;

#nullable disable

namespace NoteControl.Server.Data.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("NoteControl.Server.Data.Entities.AuditEvent", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Details")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("IpAddress")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("Timestamp")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UserId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("EventType");
                b.HasIndex("Timestamp");
                b.ToTable("AuditEvents");
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.Session", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("TEXT");
                b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("TEXT");
                b.Property<bool>("IsRevoked").HasColumnType("INTEGER");
                b.Property<DateTimeOffset>("LastActivityAt").HasColumnType("TEXT");
                b.Property<string>("TokenHash").IsRequired().HasMaxLength(128).HasColumnType("TEXT");
                b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("TEXT");
                b.Property<Guid>("UserId").HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("ExpiresAt");
                b.HasIndex("UserId");
                b.ToTable("Sessions");
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
                b.Property<DateTimeOffset?>("LastLoginAt").HasColumnType("TEXT");
                b.Property<string>("LastLoginIp").HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512).HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
                b.Property<string>("TotpSecret").HasColumnType("TEXT");
                b.Property<string>("Username").IsRequired().HasMaxLength(64).HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.Vault", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("ColorKey").HasMaxLength(32).HasColumnType("TEXT");
                b.Property<string>("IconKey").HasMaxLength(32).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("TEXT");
                b.Property<Guid>("OwnerId").HasColumnType("TEXT");
                b.Property<string>("Path").IsRequired().HasMaxLength(512).HasColumnType("TEXT");
                b.Property<string>("Scope").IsRequired().HasMaxLength(32).HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("OwnerId");
                b.HasIndex("Path").IsUnique();
                b.ToTable("Vaults");
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.VaultPermission", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("GrantedAt").HasColumnType("TEXT");
                b.Property<Guid?>("GrantedByUserId").HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
                b.Property<Guid>("UserId").HasColumnType("TEXT");
                b.Property<Guid>("VaultId").HasColumnType("TEXT");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("VaultId", "UserId").IsUnique();
                b.ToTable("VaultPermissions");
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.Session", b =>
            {
                b.HasOne("NoteControl.Server.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.Vault", b =>
            {
                b.HasOne("NoteControl.Server.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("OwnerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("NoteControl.Server.Data.Entities.VaultPermission", b =>
            {
                b.HasOne("NoteControl.Server.Data.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("NoteControl.Server.Data.Entities.Vault", null)
                    .WithMany()
                    .HasForeignKey("VaultId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
